# netlify.toml
# This file tells Netlify how to handle routes for a single-page application

[build]
  # Directory to publish (relative to root of your repo)
  publish = "dist"
  # Default build command
  command = "npm run build"

# The following redirect rule ensures that all routes are directed to index.html,
# which allows the client-side router to handle routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
