// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjzopyegzptydoerzyok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtqem9weWVnenB0eWRvZXJ6eW9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3MzMwMTAsImV4cCI6MjA1NTMwOTAxMH0.LV_LFrESkDq1SzSQK5DSzSWK6zCP50PZIrV8kS8X0Ag";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);